name: SmallRye Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 17]
    name: build with jdk ${{matrix.java}}

    steps:
      - uses: actions/checkout@v2
        name: checkout

      - uses: actions/setup-java@v1
        name: set up jdk ${{matrix.java}}
        with:
          java-version: ${{matrix.java}}

      - name: build with maven
        run: mvn -B formatter:validate install --file pom.xml

      - uses: actions/checkout@v2
        name: checkout smallrye-config
        with:
          repository: smallrye/smallrye-config
          path: smallrye-config

      - name: test with smallrye-config
        run: |
          cd smallrye-config
          mvn versions:update-property -Dproperty=version.smallrye.testing -DallowSnapshots=true -N
          git diff pom.xml
          mvn install

  quality:
    needs: [build]
    if: github.event_name == 'push' && startsWith('smallrye', github.repository)
    runs-on: ubuntu-latest
    name: quality

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: sonar
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        run: mvn -B verify --file pom.xml -Pcoverage javadoc:javadoc sonar:sonar -Dsonar.login=$SONAR_TOKEN
