name: Update Milestone

on:
  pull_request_target:
    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest
    name: pulls

    steps:
      - uses: radcortez/milestone-set-action@main
        name: milestone set
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
